### ISSUE TITLE
Rename provided sample data to 'example'

### ISSUE THREAD

**Issue by WilliamKMLai** [CEGRcode/cookiecutter-biobackend#3]
Need to better distinguish that this is example data:
sampleModel.js -> exampleModel.js
sampleController.js -> exampleController.js

samples.js updated to reflect new controller

**Comment by PrashantKuntala** [comment]
**NOT** changing to `exampleModel.js` and `exampleController.js`

_In order to conform to the NodeJS, REST API coding standards & conventions._
